version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword
      - OPENAI_API_KEY=your_openai_api_key
      - JWT_SECRET=1234567890
      - JWT_ISSUER=http://localhost:5010
      - JWT_AUDIENCE=http://localhost:4000
    ports:
      - "5010:5010"
    depends_on:
      - db

volumes:
  postgres_data: